'---------------------------'
2017-11-13T00:14:54.668Z
'url: jdbc:mysql://localhost/rollbits'
'port: 4567'
Nodes
nishant: !!com.sjsu.rollbits.discovery.Node {group: Group1, nodeId: nishant, nodeIp: 10.0.0.2,
  port: 4567, typeNode: EXTERNAL_SERVER_NODE}
Groups
Group1:
  nishant: !!com.sjsu.rollbits.discovery.Node {group: Group1, nodeId: nishant, nodeIp: 10.0.0.2,
    port: 4567, typeNode: EXTERNAL_SERVER_NODE}
'---------------------------'
2017-11-13T00:16:08.704Z
'url: jdbc:mysql://localhost/rollbits'
'port: 4567'
Nodes
rashmi: !!com.sjsu.rollbits.discovery.Node {group: Group1, nodeId: rashmi, nodeIp: 10.0.0.2,
  port: 4567, typeNode: EXTERNAL_SERVER_NODE}
Groups
Group1:
  rashmi: !!com.sjsu.rollbits.discovery.Node {group: Group1, nodeId: rashmi, nodeIp: 10.0.0.2,
    port: 4567, typeNode: EXTERNAL_SERVER_NODE}
'---------------------------'
2017-11-13T00:18:03.716Z
'url: jdbc:mysql://localhost/rollbits'
'port: 4567'
Nodes
rashmi: !!com.sjsu.rollbits.discovery.Node {group: Group1, nodeId: rashmi, nodeIp: 10.0.0.2,
  port: 4567, typeNode: EXTERNAL_SERVER_NODE}
Groups
Group1:
  rashmi: !!com.sjsu.rollbits.discovery.Node {group: Group1, nodeId: rashmi, nodeIp: 10.0.0.2,
    port: 4567, typeNode: EXTERNAL_SERVER_NODE}
'---------------------------'
2017-11-13T00:20:14.193Z
'url: jdbc:mysql://localhost/rollbits'
'port: 4567'
Nodes
Dhrumil: !!com.sjsu.rollbits.discovery.Node {group: Group1, nodeId: Dhrumil, nodeIp: 10.0.0.2,
  port: 4567, typeNode: EXTERNAL_SERVER_NODE}
rashmi: !!com.sjsu.rollbits.discovery.Node {group: Group1, nodeId: rashmi, nodeIp: 10.0.0.2,
  port: 4567, typeNode: EXTERNAL_SERVER_NODE}
Groups
Group1:
  Dhrumil: !!com.sjsu.rollbits.discovery.Node {group: Group1, nodeId: Dhrumil, nodeIp: 10.0.0.2,
    port: 4567, typeNode: EXTERNAL_SERVER_NODE}
  rashmi: !!com.sjsu.rollbits.discovery.Node {group: Group1, nodeId: rashmi, nodeIp: 10.0.0.2,
    port: 4567, typeNode: EXTERNAL_SERVER_NODE}
