url: "jdbc:mysql://localhost/rollbits"
username: "root"
password: "root"
ClusterName: "Group1"
NodeName: "nishant"
NodePort: "4567"
NodeIP: "10.0.0.18"
Secret: "secret"
UDP_IP_Broadcast: "255.255.255.255"
UDP_Port: "8888"
replicationfactor: "2"
virtualnodes: "10"
